curie_map:
  GC_ID: http://purl.obolibrary.org/obo/test1
  COMe: http://purl.obolibrary.org/obo/test2
  MBA: http://purl.obolibrary.org/obo/test3
  Reactome: http://purl.obolibrary.org/obo/test4
  PMID: http://purl.obolibrary.org/obo/test5
  WikipediaCategory: http://purl.obolibrary.org/obo/test6
  CALOHA: http://purl.obolibrary.org/obo/test7
  NIFSTD: http://purl.obolibrary.org/obo/test8
  PIRSF: http://purl.obolibrary.org/obo/test9
  Patent: http://purl.obolibrary.org/obo/test10
  TE: http://purl.obolibrary.org/obo/test11
  Drug_Central: http://purl.obolibrary.org/obo/test12
  OGEM: http://purl.obolibrary.org/obo/test13
  EHDAA2_RETIRED: http://purl.obolibrary.org/obo/test14
  OGES: http://purl.obolibrary.org/obo/test15
  MetaCyc: http://purl.obolibrary.org/obo/test16
  ncithesaurus: http://purl.obolibrary.org/obo/test17
  LINCS: http://purl.obolibrary.org/obo/test18
  Beilstein: http://purl.obolibrary.org/obo/test19
  BIRNLEX: http://purl.obolibrary.org/obo/test20
  VHOG_RETIRED: http://purl.obolibrary.org/obo/test21
  GOREL: http://purl.obolibrary.org/obo/test22
  LIPID_MAPS_instance: http://purl.obolibrary.org/obo/test23
  NLXANAT: http://purl.obolibrary.org/obo/test24
  BilaDO: http://purl.obolibrary.org/obo/test25
  Image: http://purl.obolibrary.org/obo/test26
  KUPO: http://purl.obolibrary.org/obo/test27
  Gmelin: http://purl.obolibrary.org/obo/test28
  UBERONTEMP: http://purl.obolibrary.org/obo/test29
  PANTHER: http://purl.obolibrary.org/obo/test30
  GlyGen: http://purl.obolibrary.org/obo/test31
  AEO_RETIRED: http://purl.obolibrary.org/obo/test32
  LIPID_MAPS_class: http://purl.obolibrary.org/obo/test33
  KNApSAcK: http://purl.obolibrary.org/obo/test34
  RETIRED_EHDAA2: http://purl.obolibrary.org/obo/test35
  XtroDO: http://purl.obolibrary.org/obo/test36
  GOC: http://purl.obolibrary.org/obo/test37
  HBA: http://purl.obolibrary.org/obo/test38
  NLX: http://purl.obolibrary.org/obo/test39
  DrugBank: http://purl.obolibrary.org/obo/test40
  ABA: http://purl.obolibrary.org/obo/test42
  PPDB: http://purl.obolibrary.org/obo/test43
  thefreedictionary.: http://purl.obolibrary.org/obo/test44
  BAMS: http://purl.obolibrary.org/obo/test45
  galen: http://purl.obolibrary.org/obo/test46
  MIAA: http://purl.obolibrary.org/obo/test47
  IUPHARobj: http://purl.obolibrary.org/obo/test48
  RHEA: http://purl.obolibrary.org/obo/test49
  BILS: http://purl.obolibrary.org/obo/test50
  Wikipedia: http://purl.obolibrary.org/obo/test51
  HMDB: http://purl.obolibrary.org/obo/test52
  BM: http://purl.obolibrary.org/obo/test53
  MAP: http://purl.obolibrary.org/obo/test54
  UniProtKB: http://purl.obolibrary.org/obo/test55
  BSA: http://purl.obolibrary.org/obo/test56
  KEGG: http://purl.obolibrary.org/obo/test57
  nifext: http://purl.obolibrary.org/obo/test58
  PDBeChem: http://purl.obolibrary.org/obo/test59
  OBO_REL: http://purl.obolibrary.org/obo/test60
  NIFSTD_RETIRED: http://purl.obolibrary.org/obo/test61
  snap: http://purl.obolibrary.org/obo/test62
  ILX: http://purl.obolibrary.org/obo/test63
  EC: http://purl.obolibrary.org/obo/test64
  ANISEED: http://purl.obolibrary.org/obo/test65
  CAS: http://purl.obolibrary.org/obo/test66
  GlyTouCan: http://purl.obolibrary.org/obo/test67
  NIF_Subcellular: http://purl.obolibrary.org/obo/test68
  GAID: http://purl.obolibrary.org/obo/test70
  EMAPA_RETIRED: http://purl.obolibrary.org/obo/test71
  Reaxys: http://purl.obolibrary.org/obo/test72
  DHBA: http://purl.obolibrary.org/obo/test73
  MolBase: http://purl.obolibrary.org/obo/test74
  WebElements: http://purl.obolibrary.org/obo/test75
  DMBA: http://purl.obolibrary.org/obo/test76
  ilxtr: http://purl.obolibrary.org/obo/test77
  PBA: http://purl.obolibrary.org/obo/test78
  MONDO: http://purl.obolibrary.org/obo/MONDO_
  UMLS: http://linkedlifedata.com/resource/umls/id/
  NCIT: http://purl.obolibrary.org/obo/NCIT_
  DOID: http://purl.obolibrary.org/obo/DOID_
  EFO: http://www.ebi.ac.uk/efo/EFO_
  HGNC: "http://identifiers.org/hgnc/"
  HGNC__2: "https://identifiers.org/hgnc:"
  HGNC__3: "https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:"
  HGNC_symbol: https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/
  HP: http://purl.obolibrary.org/obo/HP_
  SCTID: http://identifiers.org/snomedct/
  SCTID__2: http://snomed.info/id/
  OMIM: https://omim.org/entry/
  OMIM__2: http://identifiers.org/omim/
  OMIM__3: http://purl.obolibrary.org/obo/OMIM_
  OMIM__4: http://omim.org/entry/
  MESH: http://identifiers.org/mesh/
  Orphanet: http://www.orpha.net/ORDO/Orphanet_
  Orphanet__2: http://purl.obolibrary.org/obo/Orphanet_
  oboInOwl: http://www.geneontology.org/formats/oboInOwl#
  NCBITaxon: http://purl.obolibrary.org/obo/NCBITaxon_
  skos: http://www.w3.org/2004/02/skos/core#
  ICD10CM: http://purl.bioontology.org/ontology/ICD10CM/
  ICD10CM__2: https://icd.codes/icd10cm/
  ICD10WHO: https://icd.who.int/browse10/2019/en#/
  ICD10WHO__2: http://apps.who.int/classifications/icd10/browse/2010/en#/
  OMIMPS: https://omim.org/phenotypicSeries/PS
  MEDGEN: http://identifiers.org/medgen/
  MedDRA: http://identifiers.org/meddra/
