name: Deploy release
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'src/ontology/imports/**_import.owl'
      - 'src/ontology/components/**.owl'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.3.1
    strategy:
      max-parallel: 1
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: work around permission issue
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        
      - name: Update release files
        run: cd src/ontology/ && make ROBOT_ENV='ROBOT_JAVA_ARGS=-Xmx6G' GITHUB_ACTION=true prepare_release_fast
      
      - name: Run release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
